# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDaily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDaily

pod 'SnapKit','~> 4.0.0'
pod 'Alamofire'
pod ‘HandyJSON’
pod 'RxSwift'
pod 'RxCocoa'

end
